"""Web renderer — produces a self-contained bilingual HTML page.

Ported from the original fastpub TypeScript renderer to produce identical output.
"""
from __future__ import annotations

import html
from pathlib import Path
from typing import Any

from fastpub.models import PaperDocument, PaperFigure, WebSection


def render_web(doc: PaperDocument, zh: dict[str, Any], output_path: Path) -> Path:
    """Render PaperDocument + Chinese translation to a bilingual HTML page."""
    result = _build_html(doc, zh)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(result, encoding="utf-8")
    return output_path


def _esc(s: str) -> str:
    return html.escape(s, quote=True)


# ---------------------------------------------------------------------------
# Figure resolution
# ---------------------------------------------------------------------------

def _resolved_figures(doc: PaperDocument) -> list[dict]:
    result = []
    for fig in doc.figures:
        result.append({
            "fig": fig,
            "resolved_src": fig.src,
        })
    return result


# ---------------------------------------------------------------------------
# Section labels and icons
# ---------------------------------------------------------------------------

_SECTION_LABELS = {
    "problem": ("The Problem", "研究问题"),
    "approach": ("The Approach", "研究方法"),
    "meaning": ("Why It Matters", "研究意义"),
    "result": ("Key Results", "主要结果"),
    "limitation": ("Limitations", "局限性"),
}

_SECTION_ICONS = {
    "problem": "&#x1F50D;",   # magnifying glass
    "approach": "&#x2699;",    # gear
    "meaning": "&#x1F4A1;",   # light bulb
    "result": "&#x1F4CA;",    # bar chart
    "limitation": "&#x26A0;",  # warning
}


# ---------------------------------------------------------------------------
# HTML generation
# ---------------------------------------------------------------------------

def _build_html(doc: PaperDocument, zh: dict[str, Any]) -> str:
    zh_meta = zh.get("meta", {})
    zh_hook = zh.get("hook", doc.hook)
    zh_web_sections = {s.get("type", ""): s for s in zh.get("webSections", zh.get("web_sections", []))}
    zh_figures = {f.get("id", ""): f for f in zh.get("figures", [])}
    figures = [f for f in _resolved_figures(doc)]

    # Header
    venue_html = ""
    if doc.meta.venue:
        year_part = f" ({doc.meta.year})" if doc.meta.year else ""
        venue_html = f'  <p class="venue">{_esc(doc.meta.venue)}{year_part}</p>'

    keywords_html = ""
    if doc.meta.keywords:
        tags = " ".join(f'<span class="tag">{_esc(k)}</span>' for k in doc.meta.keywords)
        keywords_html = f'  <p class="keywords">{tags}</p>'

    # Web sections
    sections_html = "\n".join(
        _build_section_html(s, zh_web_sections.get(s.type, {}))
        for s in doc.web_sections
    )

    # Figures
    figures_html = _build_figures_html(figures, zh_figures) if figures else ""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{_esc(doc.meta.title)}</title>
{_build_styles()}
</head>
<body>

<nav class="lang-toggle">
  <button id="btn-en" class="active" onclick="setLang('en')">EN</button>
  <button id="btn-zh" onclick="setLang('zh')">中文</button>
</nav>

<header>
  <h1>
    <span class="en">{_esc(doc.meta.title)}</span>
    <span class="zh" hidden>{_esc(zh_meta.get("title", doc.meta.title))}</span>
  </h1>
  <p class="authors">{_esc(", ".join(doc.meta.authors))}</p>
{venue_html}
{keywords_html}
</header>

<section class="hook">
  <blockquote>
    <span class="en">{_esc(doc.hook)}</span>
    <span class="zh" hidden>{_esc(zh_hook)}</span>
  </blockquote>
</section>

<section class="abstract">
  <h2>
    <span class="en">Abstract</span>
    <span class="zh" hidden>摘要</span>
  </h2>
  <p>
    <span class="en">{_esc(doc.meta.abstract)}</span>
    <span class="zh" hidden>{_esc(zh_meta.get("abstract", ""))}</span>
  </p>
</section>

{sections_html}

{figures_html}

<footer>
  <p>Generated by <strong>FastPub</strong></p>
</footer>

{_build_script()}
</body>
</html>"""


def _build_section_html(s: WebSection, zh_s: dict) -> str:
    en_label, zh_label = _SECTION_LABELS.get(s.type, (s.type.title(), s.type.title()))
    zh_summary = zh_s.get("summary", s.summary)
    zh_sub_issues = zh_s.get("subIssues", zh_s.get("sub_issues", []))

    sub_items = []
    for i, si in enumerate(s.sub_issues):
        zh_si = zh_sub_issues[i] if i < len(zh_sub_issues) else {}
        sub_items.append(f"""<div class="sub-issue">
      <h4>
        <span class="en">{_esc(si.title)}</span>
        <span class="zh" hidden>{_esc(zh_si.get("title", si.title))}</span>
      </h4>
      <p>
        <span class="en">{_esc(si.description)}</span>
        <span class="zh" hidden>{_esc(zh_si.get("description", si.description))}</span>
      </p>
    </div>""")

    sub_html = "\n    ".join(sub_items)

    return f"""<section class="web-section section-{s.type}">
  <h2>
    <span class="en">{en_label}</span>
    <span class="zh" hidden>{zh_label}</span>
    <span class="badge badge-{s.type}">{s.type}</span>
  </h2>
  <p class="section-summary">
    <span class="en">{_esc(s.summary)}</span>
    <span class="zh" hidden>{_esc(zh_summary)}</span>
  </p>
  <div class="sub-issues">
    {sub_html}
  </div>
</section>"""


def _build_figures_html(figures: list[dict], zh_figures: dict) -> str:
    items = "\n    ".join(_figure_item(f, zh_figures) for f in figures)
    return f"""<section class="figures">
  <h2>
    <span class="en">Figures</span>
    <span class="zh" hidden>图表</span>
  </h2>
  <div class="figure-grid">
    {items}
  </div>
</section>"""


def _figure_item(f: dict, zh_figures: dict) -> str:
    fig: PaperFigure = f["fig"]
    src = f["resolved_src"]
    zh_fig = zh_figures.get(fig.id, {})
    zh_caption = zh_fig.get("caption", fig.caption)
    zh_desc = zh_fig.get("aiDescription", fig.ai_description)
    return f"""<figure>
      <img src="{src}" alt="{_esc(fig.ai_description)}" loading="lazy">
      <figcaption>
        <strong>{_esc(fig.id)}</strong>
        <span class="en">{_esc(fig.caption)}</span>
        <span class="zh" hidden>{_esc(zh_caption)}</span>
        <p class="ai-desc">
          <span class="en">{_esc(fig.ai_description)}</span>
          <span class="zh" hidden>{_esc(zh_desc)}</span>
        </p>
      </figcaption>
    </figure>"""


def _build_styles() -> str:
    return """<style>
  :root {
    --bg: #fafafa; --fg: #1a1a1a; --accent: #2563eb;
    --card-bg: #fff; --border: #e5e7eb; --muted: #6b7280;
    --max-w: 800px;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #111; --fg: #e5e5e5; --accent: #60a5fa;
      --card-bg: #1a1a1a; --border: #333; --muted: #9ca3af;
    }
  }
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: var(--bg); color: var(--fg);
    line-height: 1.7; padding: 2rem 1rem; max-width: var(--max-w); margin: 0 auto;
  }
  header { text-align: center; margin-bottom: 2.5rem; }
  h1 { font-size: 1.75rem; margin-bottom: 0.5rem; line-height: 1.3; }
  .authors { color: var(--muted); margin-bottom: 0.25rem; }
  .venue { color: var(--muted); font-style: italic; margin-bottom: 0.5rem; }
  .keywords { display: flex; flex-wrap: wrap; gap: 0.4rem; justify-content: center; }
  .tag {
    background: var(--accent); color: #fff; padding: 0.15rem 0.5rem;
    border-radius: 999px; font-size: 0.75rem;
  }

  .lang-toggle {
    position: fixed; top: 1rem; right: 1rem; z-index: 100;
    display: flex; gap: 0; border-radius: 6px; overflow: hidden;
    border: 1px solid var(--border);
  }
  .lang-toggle button {
    border: none; padding: 0.35rem 0.75rem; cursor: pointer;
    background: var(--card-bg); color: var(--fg); font-size: 0.85rem;
  }
  .lang-toggle button.active { background: var(--accent); color: #fff; }

  .hook blockquote {
    font-size: 1.2rem; font-style: italic; border-left: 4px solid var(--accent);
    padding: 0.75rem 1rem; margin: 1.5rem 0; background: var(--card-bg);
    border-radius: 0 8px 8px 0;
  }

  .abstract, .web-section, .figures { margin: 2rem 0; }
  h2 { font-size: 1.3rem; margin-bottom: 0.75rem; display: flex; align-items: center; gap: 0.5rem; flex-wrap: wrap; }
  .badge {
    font-size: 0.65rem; padding: 0.15rem 0.45rem; border-radius: 4px;
    text-transform: uppercase; font-weight: 600; letter-spacing: 0.04em;
  }
  .badge-problem { background: #fecaca; color: #991b1b; }
  .badge-approach { background: #bfdbfe; color: #1e40af; }
  .badge-meaning { background: #e9d5ff; color: #6b21a8; }
  .badge-result { background: #bbf7d0; color: #166534; }
  .badge-limitation { background: #fde68a; color: #92400e; }

  .section-summary {
    font-size: 1rem; line-height: 1.7; margin-bottom: 1rem;
    color: var(--fg);
  }

  .sub-issues {
    display: grid; grid-template-columns: 1fr; gap: 0.75rem;
  }
  .sub-issue {
    background: var(--card-bg); border: 1px solid var(--border);
    border-radius: 8px; padding: 0.75rem 1rem;
  }
  .sub-issue h4 {
    font-size: 0.9rem; font-weight: 600; margin-bottom: 0.3rem;
    color: var(--accent);
  }
  .sub-issue p { font-size: 0.85rem; color: var(--fg); line-height: 1.6; }

  .figure-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1.5rem; }
  figure { background: var(--card-bg); border: 1px solid var(--border); border-radius: 8px; overflow: hidden; }
  figure img { width: 100%; height: auto; display: block; }
  figcaption { padding: 0.75rem; font-size: 0.85rem; }
  .ai-desc { color: var(--muted); margin-top: 0.3rem; font-size: 0.8rem; }

  footer { margin-top: 3rem; text-align: center; color: var(--muted); font-size: 0.8rem; }
</style>"""


def _build_script() -> str:
    return """<script>
function setLang(lang) {
  document.querySelectorAll('.en').forEach(el => el.hidden = lang !== 'en');
  document.querySelectorAll('.zh').forEach(el => el.hidden = lang !== 'zh');
  document.getElementById('btn-en').classList.toggle('active', lang === 'en');
  document.getElementById('btn-zh').classList.toggle('active', lang === 'zh');
  document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
}
</script>"""
