"""Web renderer — produces a self-contained bilingual HTML page.

Ported from the original fastpub TypeScript renderer to produce identical output.
"""
from __future__ import annotations

import html
from pathlib import Path
from typing import Any

from fastpub.models import PaperDocument, PaperFigure


def render_web(doc: PaperDocument, zh: dict[str, Any], output_path: Path) -> Path:
    """Render PaperDocument + Chinese translation to a bilingual HTML page."""
    result = _build_html(doc, zh)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(result, encoding="utf-8")
    return output_path


def _esc(s: str) -> str:
    return html.escape(s, quote=True)


# ---------------------------------------------------------------------------
# Figure resolution — prefer generatedVisual over original when available
# ---------------------------------------------------------------------------

def _resolved_figures(doc: PaperDocument) -> list[dict]:
    gen_map = {v.for_figure_id: v for v in doc.generated_visuals}
    result = []
    for fig in doc.figures:
        gen = gen_map.get(fig.id)
        result.append({
            "fig": fig,
            "resolved_src": gen.src if gen else fig.src,
            "is_generated": gen is not None,
        })
    return result


# ---------------------------------------------------------------------------
# HTML generation — matches original fastpub output
# ---------------------------------------------------------------------------

def _build_html(doc: PaperDocument, zh: dict[str, Any]) -> str:
    zh_figures = {f["id"]: f for f in zh.get("figures", [])}
    figures = [f for f in _resolved_figures(doc) if f["fig"].usability != "skip"]
    for f in figures:
        f["zh"] = zh_figures.get(f["fig"].id, {})
    zh_narr = zh.get("narrative", {})
    zh_meta = zh.get("meta", {})
    zh_sections = zh.get("sections", [])

    # Header
    venue_html = ""
    if doc.meta.venue:
        year_part = f" ({doc.meta.year})" if doc.meta.year else ""
        venue_html = f'  <p class="venue">{_esc(doc.meta.venue)}{year_part}</p>'

    keywords_html = ""
    if doc.meta.keywords:
        tags = " ".join(f'<span class="tag">{_esc(k)}</span>' for k in doc.meta.keywords)
        keywords_html = f'  <p class="keywords">{tags}</p>'

    # Narrative
    narrative_cards = _narrative_card("Problem", "研究问题",
                                      doc.narrative.problem, zh_narr.get("problem", ""))
    narrative_cards += _narrative_card("Approach", "研究方法",
                                       doc.narrative.approach, zh_narr.get("approach", ""))
    narrative_cards += _narrative_card("Significance", "研究意义",
                                       doc.narrative.significance, zh_narr.get("significance", ""))

    # Results list
    zh_results = zh_narr.get("results", [])
    results_items = "\n      ".join(
        f'<li><span class="en">{_esc(r)}</span>'
        f'<span class="zh" hidden>{_esc(zh_results[i] if i < len(zh_results) else r)}</span></li>'
        for i, r in enumerate(doc.narrative.results)
    )

    # Sections
    sections_html = "\n".join(_build_section_html(s, zh_sections) for s in doc.sections)

    # Figures
    figures_html = _build_figures_html(figures) if figures else ""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{_esc(doc.meta.title)}</title>
{_build_styles()}
</head>
<body>

<nav class="lang-toggle">
  <button id="btn-en" class="active" onclick="setLang('en')">EN</button>
  <button id="btn-zh" onclick="setLang('zh')">中文</button>
</nav>

<header>
  <h1>
    <span class="en">{_esc(doc.meta.title)}</span>
    <span class="zh" hidden>{_esc(zh_meta.get("title", doc.meta.title))}</span>
  </h1>
  <p class="authors">{_esc(", ".join(doc.meta.authors))}</p>
{venue_html}
{keywords_html}
</header>

<section class="narrative">
  <blockquote>
    <span class="en">{_esc(doc.narrative.hook)}</span>
    <span class="zh" hidden>{_esc(zh_narr.get("hook", doc.narrative.hook))}</span>
  </blockquote>

  <div class="narrative-grid">
    {narrative_cards}
  </div>

  <div class="results">
    <h3>
      <span class="en">Key Results</span>
      <span class="zh" hidden>主要成果</span>
    </h3>
    <ul>
      {results_items}
    </ul>
  </div>
</section>

<section class="abstract">
  <h2>
    <span class="en">Abstract</span>
    <span class="zh" hidden>摘要</span>
  </h2>
  <p>
    <span class="en">{_esc(doc.meta.abstract)}</span>
    <span class="zh" hidden>{_esc(zh_meta.get("abstract", ""))}</span>
  </p>
</section>

{sections_html}

{figures_html}

<footer>
  <p>Generated by <strong>FastPub</strong></p>
</footer>

{_build_script()}
</body>
</html>"""


def _narrative_card(label: str, zh_label: str, en: str, zh_text: str) -> str:
    return f"""<div class="card">
      <h4>
        <span class="en">{label}</span>
        <span class="zh" hidden>{zh_label}</span>
      </h4>
      <p>
        <span class="en">{_esc(en)}</span>
        <span class="zh" hidden>{_esc(zh_text)}</span>
      </p>
    </div>
    """


def _build_section_html(s, zh_sections: list[dict]) -> str:
    zh_s = next((zs for zs in zh_sections if zs.get("id") == s.id), {})
    zh_key_points = zh_s.get("keyPoints", zh_s.get("key_points", []))
    importance_class = " low-importance" if s.importance == "low" else ""

    key_points_html = "\n    ".join(
        f'<li><span class="en">{_esc(kp)}</span>'
        f'<span class="zh" hidden>{_esc(zh_key_points[i] if i < len(zh_key_points) else kp)}</span></li>'
        for i, kp in enumerate(s.key_points)
    )

    return f"""<section class="paper-section{importance_class}">
  <h2>
    <span class="en">{_esc(s.title)}</span>
    <span class="zh" hidden>{_esc(zh_s.get("title", s.title))}</span>
    <span class="badge badge-{s.type}">{s.type}</span>
  </h2>
  <p>
    <span class="en">{_esc(s.summary)}</span>
    <span class="zh" hidden>{_esc(zh_s.get("summary", s.summary))}</span>
  </p>
  <ul>
    {key_points_html}
  </ul>
</section>"""


def _build_figures_html(figures: list[dict]) -> str:
    items = "\n    ".join(_figure_item(f) for f in figures)
    return f"""<section class="figures">
  <h2>
    <span class="en">Figures</span>
    <span class="zh" hidden>图表</span>
  </h2>
  <div class="figure-grid">
    {items}
  </div>
</section>"""


def _figure_item(f: dict) -> str:
    fig: PaperFigure = f["fig"]
    zh_fig: dict = f.get("zh", {})
    src = f["resolved_src"]
    ai_badge = '\n      <span class="ai-badge">Simplified</span>' if f["is_generated"] else ""
    zh_caption = zh_fig.get("caption", fig.caption)
    zh_ai_desc = zh_fig.get("aiDescription", zh_fig.get("ai_description", fig.ai_description))
    return f"""<figure>
      <img src="{src}" alt="{_esc(fig.ai_description)}" loading="lazy">{ai_badge}
      <figcaption>
        <strong>{_esc(fig.id)}</strong>
        <span class="en">{_esc(fig.caption)}</span>
        <span class="zh" hidden>{_esc(zh_caption)}</span>
        <p class="ai-desc">
          <span class="en">{_esc(fig.ai_description)}</span>
          <span class="zh" hidden>{_esc(zh_ai_desc)}</span>
        </p>
      </figcaption>
    </figure>"""


def _build_styles() -> str:
    return """<style>
  :root {
    --bg: #fafafa; --fg: #1a1a1a; --accent: #2563eb;
    --card-bg: #fff; --border: #e5e7eb; --muted: #6b7280;
    --max-w: 800px;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #111; --fg: #e5e5e5; --accent: #60a5fa;
      --card-bg: #1a1a1a; --border: #333; --muted: #9ca3af;
    }
  }
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: var(--bg); color: var(--fg);
    line-height: 1.7; padding: 2rem 1rem; max-width: var(--max-w); margin: 0 auto;
  }
  header { text-align: center; margin-bottom: 2.5rem; }
  h1 { font-size: 1.75rem; margin-bottom: 0.5rem; line-height: 1.3; }
  .authors { color: var(--muted); margin-bottom: 0.25rem; }
  .venue { color: var(--muted); font-style: italic; margin-bottom: 0.5rem; }
  .keywords { display: flex; flex-wrap: wrap; gap: 0.4rem; justify-content: center; }
  .tag {
    background: var(--accent); color: #fff; padding: 0.15rem 0.5rem;
    border-radius: 999px; font-size: 0.75rem;
  }

  .lang-toggle {
    position: fixed; top: 1rem; right: 1rem; z-index: 100;
    display: flex; gap: 0; border-radius: 6px; overflow: hidden;
    border: 1px solid var(--border);
  }
  .lang-toggle button {
    border: none; padding: 0.35rem 0.75rem; cursor: pointer;
    background: var(--card-bg); color: var(--fg); font-size: 0.85rem;
  }
  .lang-toggle button.active { background: var(--accent); color: #fff; }

  .narrative blockquote {
    font-size: 1.2rem; font-style: italic; border-left: 4px solid var(--accent);
    padding: 0.75rem 1rem; margin: 1.5rem 0; background: var(--card-bg);
    border-radius: 0 8px 8px 0;
  }
  .narrative-grid {
    display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
    gap: 1rem; margin: 1.5rem 0;
  }
  .card {
    background: var(--card-bg); border: 1px solid var(--border);
    border-radius: 8px; padding: 1rem;
  }
  .card h4 { color: var(--accent); margin-bottom: 0.4rem; font-size: 0.9rem; text-transform: uppercase; letter-spacing: 0.05em; }

  .results { margin: 1.5rem 0; }
  .results h3 { margin-bottom: 0.5rem; }
  .results ul { padding-left: 1.5rem; }
  .results li { margin-bottom: 0.3rem; }

  .abstract, .paper-section, .figures { margin: 2rem 0; }
  h2 { font-size: 1.3rem; margin-bottom: 0.75rem; display: flex; align-items: center; gap: 0.5rem; flex-wrap: wrap; }
  .badge {
    font-size: 0.65rem; padding: 0.15rem 0.45rem; border-radius: 4px;
    text-transform: uppercase; font-weight: 600; letter-spacing: 0.04em;
  }
  .badge-problem { background: #fecaca; color: #991b1b; }
  .badge-method { background: #bfdbfe; color: #1e40af; }
  .badge-experiment { background: #fde68a; color: #92400e; }
  .badge-result { background: #bbf7d0; color: #166534; }
  .badge-discussion { background: #e9d5ff; color: #6b21a8; }
  .badge-other { background: var(--border); color: var(--muted); }

  .low-importance { opacity: 0.7; }
  .paper-section ul { padding-left: 1.5rem; margin-top: 0.5rem; }
  .paper-section li { margin-bottom: 0.25rem; }

  .figure-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1.5rem; }
  figure { background: var(--card-bg); border: 1px solid var(--border); border-radius: 8px; overflow: hidden; }
  figure img { width: 100%; height: auto; display: block; }
  figcaption { padding: 0.75rem; font-size: 0.85rem; }
  .ai-desc { color: var(--muted); margin-top: 0.3rem; font-size: 0.8rem; }

  footer { margin-top: 3rem; text-align: center; color: var(--muted); font-size: 0.8rem; }
</style>"""


def _build_script() -> str:
    return """<script>
function setLang(lang) {
  document.querySelectorAll('.en').forEach(el => el.hidden = lang !== 'en');
  document.querySelectorAll('.zh').forEach(el => el.hidden = lang !== 'zh');
  document.getElementById('btn-en').classList.toggle('active', lang === 'en');
  document.getElementById('btn-zh').classList.toggle('active', lang === 'zh');
  document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
}
</script>"""
