"""Web renderer — produces a self-contained bilingual HTML page.

Ported from the original fastpub TypeScript renderer to produce identical output.
"""
from __future__ import annotations

import html
from pathlib import Path
from typing import Any

from fastpub.models import PaperDocument, PaperFigure, WebSection
from fastpub.render.theme import WARM_SERIF, build_web_css


def render_web(doc: PaperDocument, zh: dict[str, Any], output_path: Path) -> Path:
    """Render PaperDocument + Chinese translation to a bilingual HTML page."""
    result = _build_html(doc, zh)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(result, encoding="utf-8")
    return output_path


def _esc(s: str) -> str:
    return html.escape(s, quote=True)


# ---------------------------------------------------------------------------
# Figure resolution
# ---------------------------------------------------------------------------

def _resolved_figures(doc: PaperDocument) -> list[dict]:
    result = []
    for fig in doc.figures:
        result.append({
            "fig": fig,
            "resolved_src": fig.src,
        })
    return result


# ---------------------------------------------------------------------------
# Section labels and icons
# ---------------------------------------------------------------------------

_SECTION_LABELS = {
    "problem": ("The Problem", "研究问题"),
    "approach": ("The Approach", "研究方法"),
    "meaning": ("Why It Matters", "研究意义"),
    "result": ("Key Results", "主要结果"),
    "limitation": ("Limitations", "局限性"),
}

_BADGE_CLASSES = {
    "problem": "badge-problem",
    "approach": "badge-method",
    "meaning": "badge-discussion",
    "result": "badge-result",
    "limitation": "badge-other",
}


# ---------------------------------------------------------------------------
# HTML generation
# ---------------------------------------------------------------------------

def _build_html(doc: PaperDocument, zh: dict[str, Any]) -> str:
    zh_meta = zh.get("meta", {})
    zh_hook = zh.get("hook", doc.hook)
    zh_web_sections = {s.get("type", ""): s for s in zh.get("webSections", zh.get("web_sections", []))}
    zh_figures = {f.get("id", ""): f for f in zh.get("figures", [])}
    figures = [f for f in _resolved_figures(doc)]

    theme = WARM_SERIF

    # Header parts
    venue_html = ""
    if doc.meta.venue:
        year_part = f" ({doc.meta.year})" if doc.meta.year else ""
        venue_html = f'  <p class="venue">{_esc(doc.meta.venue)}{year_part}</p>'

    keywords_html = ""
    if doc.meta.keywords:
        tags = " ".join(f'<span class="tag">{_esc(k)}</span>' for k in doc.meta.keywords)
        keywords_html = f'  <div class="keywords">{tags}</div>'

    # Narrative cards (brief overview per section)
    narrative_cards = "\n".join(
        _build_narrative_card(s, zh_web_sections.get(s.type, {}))
        for s in doc.web_sections
    )

    # Paper sections (detailed with badges and bullet lists)
    sections_html = "\n".join(
        _build_section_html(s, zh_web_sections.get(s.type, {}))
        for s in doc.web_sections
    )

    # Figures
    figures_html = _build_figures_html(figures, zh_figures) if figures else ""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{_esc(doc.meta.title)}</title>
{build_web_css(theme)}
</head>
<body>

<nav class="lang-toggle">
  <button id="btn-en" class="active" onclick="setLang('en')">EN</button>
  <button id="btn-zh" onclick="setLang('zh')">中文</button>
</nav>

<header>
  <h1>
    <span class="en">{_esc(doc.meta.title)}</span>
    <span class="zh" hidden>{_esc(zh_meta.get("title", doc.meta.title))}</span>
  </h1>
  <p class="authors">{_esc(", ".join(doc.meta.authors))}</p>
{venue_html}
{keywords_html}
</header>

<section class="narrative">
  <blockquote>
    <span class="en">{_esc(doc.hook)}</span>
    <span class="zh" hidden>{_esc(zh_hook)}</span>
  </blockquote>

  <div class="narrative-grid">
{narrative_cards}
  </div>
</section>

<section class="abstract">
  <h2>
    <span class="en">Abstract</span>
    <span class="zh" hidden>摘要</span>
  </h2>
  <p>
    <span class="en">{_esc(doc.meta.abstract)}</span>
    <span class="zh" hidden>{_esc(zh_meta.get("abstract", ""))}</span>
  </p>
</section>

{sections_html}

{figures_html}

<footer>
  Generated by FastPub
</footer>

{_build_script()}
</body>
</html>"""


def _build_narrative_card(s: WebSection, zh_s: dict) -> str:
    en_label, zh_label = _SECTION_LABELS.get(s.type, (s.type.title(), s.type.title()))
    zh_summary = zh_s.get("summary", s.summary)
    return f"""    <div class="card">
      <h4>
        <span class="en">{en_label}</span>
        <span class="zh" hidden>{zh_label}</span>
      </h4>
      <p>
        <span class="en">{_esc(s.summary)}</span>
        <span class="zh" hidden>{_esc(zh_summary)}</span>
      </p>
    </div>"""


def _build_section_html(s: WebSection, zh_s: dict) -> str:
    en_label, zh_label = _SECTION_LABELS.get(s.type, (s.type.title(), s.type.title()))
    badge_cls = _BADGE_CLASSES.get(s.type, "badge-other")
    zh_sub_issues = zh_s.get("subIssues", zh_s.get("sub_issues", []))

    bullet_items = []
    for i, si in enumerate(s.sub_issues):
        zh_si = zh_sub_issues[i] if i < len(zh_sub_issues) else {}
        bullet_items.append(
            f'    <li><span class="en">{_esc(si.description)}</span>'
            f'<span class="zh" hidden>{_esc(zh_si.get("description", si.description))}</span></li>'
        )

    bullets_html = "\n".join(bullet_items)

    return f"""<section class="paper-section">
  <h2>
    <span class="en">{en_label}</span>
    <span class="zh" hidden>{zh_label}</span>
    <span class="badge {badge_cls}">{s.type}</span>
  </h2>
  <ul>
{bullets_html}
  </ul>
</section>"""


def _build_figures_html(figures: list[dict], zh_figures: dict) -> str:
    items = "\n    ".join(_figure_item(f, zh_figures) for f in figures)
    return f"""<section class="figures">
  <h2>
    <span class="en">Figures</span>
    <span class="zh" hidden>图表</span>
  </h2>
  <div class="figure-grid">
    {items}
  </div>
</section>"""


def _figure_item(f: dict, zh_figures: dict) -> str:
    fig: PaperFigure = f["fig"]
    src = f["resolved_src"]
    zh_fig = zh_figures.get(fig.id, {})
    zh_caption = zh_fig.get("caption", fig.caption)
    zh_desc = zh_fig.get("aiDescription", fig.ai_description)
    return f"""<figure>
      <img src="{src}" alt="{_esc(fig.ai_description)}" loading="lazy">
      <figcaption>
        <strong>{_esc(fig.id)}</strong>
        <span class="en">{_esc(fig.caption)}</span>
        <span class="zh" hidden>{_esc(zh_caption)}</span>
        <p class="ai-desc">
          <span class="en">{_esc(fig.ai_description)}</span>
          <span class="zh" hidden>{_esc(zh_desc)}</span>
        </p>
      </figcaption>
    </figure>"""



def _build_script() -> str:
    return """<script>
function setLang(lang) {
  document.querySelectorAll('.en').forEach(el => el.hidden = lang !== 'en');
  document.querySelectorAll('.zh').forEach(el => el.hidden = lang !== 'zh');
  document.getElementById('btn-en').classList.toggle('active', lang === 'en');
  document.getElementById('btn-zh').classList.toggle('active', lang === 'zh');
  document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
}
</script>"""
